### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by EpokK** [bdavidxyz/white-angularjs-app#1]
Lorsque je lance ta white app j'ai une erreur sur la page directement : 

Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin. file://localhost/Users/richardtetaz/Desktop/white-angularjs-app-master/partials/partial1.html
XMLHttpRequest cannot load file://localhost/Users/richardtetaz/Desktop/white-angularjs-app-master/partials/partial1.html. Origin null is not allowed by Access-Control-Allow-Origin.

**Comment by bdavidxyz** [comment]
L'accès se fait par fichier uniquement, donc avec un Firefox ou un Chrome avec l'option --allow-files-access-from-file
